### ISSUE TITLE
Inconsistency with "Go To Vault" button in top bar between home page and legal page

### ISSUE THREAD

**Issue by HightechTR** [IngeniousCoder/PassGuard-Issues#13]
The "Go To Vault" button is written as follows on the home page:
![image](https://user-images.githubusercontent.com/34486197/214608767-760ba2e3-77f6-41d6-8494-980b0ae0429a.png)

On the legal page, the button is instead just "Vault":
![image](https://user-images.githubusercontent.com/34486197/214608881-3da3d890-e3a5-49c6-96bc-e273802394df.png)

**Comment by IngeniousCoder** [comment]
fixed
