### ISSUE TITLE
create password Master Password going next line.

### ISSUE THREAD

**Issue by LoofyDoofy** [IngeniousCoder/PassGuard-Issues#3]

**Comment by IngeniousCoder** [comment]
hello provide picture etc pls

**Comment by LoofyDoofy** [comment]
![image](https://user-images.githubusercontent.com/88327316/214594024-43110619-ee43-48f0-b09a-6d061a67e20a.png)

**Comment by IngeniousCoder** [comment]
visual issue by template, wontfix
