### ISSUE TITLE
Footer on legal page does not match footer on home

### ISSUE THREAD

**Issue by HightechTR** [IngeniousCoder/PassGuard-Issues#5]
Footer on the legal page (accessed via "Legal Notices" button at footer) has different information from the footer on the home page.

Email Address:
Instead of elton@eltontay.com, it is 20210729P@mymail.nyp.edu.sg

Copyright Info:
Instead of "Elton Tay and Co", it is "Free HTML Templates"

**Comment by IngeniousCoder** [comment]
fixed
