### ISSUE TITLE
Inconsistency with behaviour of call phone number buttons

### ISSUE THREAD

**Issue by HightechTR** [IngeniousCoder/PassGuard-Issues#6]
On the home page, there are 2 phone number buttons.
One located at the top bar:
![image](https://user-images.githubusercontent.com/34486197/214597008-80f952bf-b8ba-4677-8d5b-10a80fc1d8f8.png)
and one located on the footer.

Both buttons do not have the same behaviour when clicked.

The button on the top bar only leads to the page that is currently viewed (button on home page leads to home page, button on legal page leads to legal page)

The button in the footer provides a prompt to call the number.

**Comment by IngeniousCoder** [comment]
fixed
