### ISSUE TITLE
vault/password password123 should not be a moderate password ;d

### ISSUE THREAD

**Issue by LoofyDoofy** [IngeniousCoder/PassGuard-Issues#7]
![image](https://user-images.githubusercontent.com/88327316/214598197-579678e7-d5f6-458e-ac7f-b14407a2cd57.png)

**Comment by IngeniousCoder** [comment]
need to fine tune the thing, you go fine tune and PR

**Comment by HightechTR** [comment]
"Password@123" was listed as STRONG, and "000000000" was listed as MODERATE
