### ISSUE TITLE
Entering a single letter/number in 2FA leads to 404

### ISSUE THREAD

**Issue by HightechTR** [IngeniousCoder/PassGuard-Issues#9]
When given the page to enter the 2FA code to login, entering a single upper or lowercase letter or number into the field and clicking "Sign In" or pressing Enter leads to a 404 page.

This does not work with 2 characters or more, or with special characters, as they will give the "invalid code" error as intended.

**Comment by IngeniousCoder** [comment]
wontfix, seems like PyOTP problem
